### ISSUE TITLE
Vital missing info

### ISSUE THREAD

**Issue by Synchro** [Ilyes512/ansible-role-timezone#2]
The readme has the variables marked as `[TODO]`. This is missing the one vital piece of info to make this role usable: the variable name to put the zone in. It is in fact `locale_timezone`, and it defaults to `Europe/Amsterdam`. That's not a very sensible default - better would be `Etc/UTC`.

**Comment by Ilyes512** [comment]
I agree. Made this a while ago for my self. I you make a pr I will merge it :)

**Comment by Ilyes512** [comment]
I have also added a 1.0.0 tag. Thanks for your PR!
